ihome/order/__init__.py
from flask import Blueprint

order_blue = Blueprint('order', __name__)

from . import views

ihome/order/views.py
from datetime import date, datetime
from operator import or_, and_

from flask import request, render_template, session, jsonify
from flask_login import login_required, current_user
from sqlalchemy import desc

from utils.models import House, Order
from utils.status_code import *
from . import order_blue


@order_blue.route('/my_order/')
@login_required
def my_order():
    if request.method == 'GET':
        return render_template('orders.html')


@order_blue.route('/order_add/', methods=['POST'])
@login_required
def order_add():
    if request.method == 'POST':
        data = request.form
        order = Order(**data)
        order.user_id = current_user.id
        order.add_update()
        return jsonify({"code": OK})


@order_blue.route('/my_order_info/')
@login_required
def my_order_info():
    if request.method == 'GET':
        user_id = current_user.id
        orders = Order.query.filter(Order.user_id == user_id).all()
        info = [order.to_dict() for order in orders]
        return jsonify(info)


@order_blue.route('/comment_order/', methods=['POST'])
@login_required
def comment_order():
    if request.method == 'POST':
        order_id = int(request.form.get('order_id'))
        comment = request.form.get('comment')
        # 状态变更，从待评价到已完成
        order = Order.query.get(order_id)
        order.status = "COMPLETE"
        order.comment = comment
        # 更新房源出租次数
        house = House.query.filter(House.id == order.house_id).first()
        house.order_count = int(house.order_count) + 1
        house.add_update()
        order.add_update()
        return jsonify({'code': OK})


@order_blue.route('/cu_order/')
@login_required
def cu_order():
    if request.method == 'GET':
        return render_template('lorders.html')


@order_blue.route('/cu_order_info/')
@login_required
def cu_order_info():
    if request.method == 'GET':
        houses = House.query.filter_by(user_id=current_user.id).all()
        house_ids = [house.id for house in houses]
        orders = Order.query.filter(Order.house_id.in_(house_ids)).all()
        orders_info = [order.to_dict() for order in orders]
        return jsonify(orders=orders_info)


@order_blue.route('/accept_order/', methods=['POST'])
@login_required
def accept_order():
    if request.method == 'POST':
        order_id = int(request.form.get('order_id'))
        # 状态变更，从待接单到待评价
        order = Order.query.get(order_id)
        order.status = "WAIT_COMMENT"
        order.add_update()
        return jsonify({'code': OK})


@order_blue.route('/reject_order/', methods=['POST'])
@login_required
def reject_order():
    if request.method == 'POST':
        order_id = int(request.form.get('order_id'))
        comment = request.form.get('reject_reason')
        # 状态变更，从待接单到已拒单
        order = Order.query.get(order_id)
        order.status = "REJECTED"
        order.comment = comment
        order.add_update()
        return jsonify({'code': OK})


@order_blue.route('/booking/<int:house_id>/')
@login_required
def booking(house_id):
    if request.method == 'GET':
        session["house_id"] = house_id
        return render_template('booking.html')


@order_blue.route('/booking_info/')
@login_required
def booking_info():
    if request.method == 'GET':
        house_id = int(session.get("house_id"))
        house = House.query.get(house_id)
        info = house.to_dict()
        return jsonify(info)


@order_blue.route('/index/')
def index():
    if request.method == 'GET':
        return render_template('index.html')


@order_blue.route('/index_info/')
def index_info():
    if request.method == 'GET':
        orders = Order.query.all()
        booking_houses_id = [order.house_id for order in orders if order.status in ["WAIT_PAYMENT", "PAID", "WAIT_ACCEPT"]]
        houses = House.query.filter(~House.id.in_(booking_houses_id))
        final_houses = houses.order_by(desc('update_time'))
        info = [house.to_dict() for house in final_houses]
        return jsonify(info)


@order_blue.route('/check_user/')
@login_required
def check_user():
    if request.method == 'GET':
        user = current_user
        if user.is_authenticated:
            info = user.to_basic_dict()
            return jsonify({"code": OK, "info": info})
        else:
            return jsonify({"code": USER_HAS_NOT_LOGIN})


@order_blue.route('/search/')
def search():
    if request.method == 'GET':
        return render_template('search.html')


@order_blue.route('/search_info/', methods=['POST'])
def search_info():
    if request.method == 'POST':
        area_id = request.form.get('aid')
        start_time = request.form.get('sd')
        end_time = request.form.get('ed')
        if not start_time:
            start_time = date.today().strftime("%Y-%m-%d")
        sk = request.form.get('sk')
        # p = request.form.get('p')
        if end_time:
            start_date = datetime.strptime(start_time, '%Y-%m-%d')
            end_date = datetime.strptime(end_time, "%Y-%m-%d")
            differ_days = int((end_date-start_date).days)
            # 如果用户输入有开始和结束时间则显示数据库该分段的信息
            houses_first = House.query.filter(or_(and_(House.min_days <= differ_days, House.max_days >= differ_days),
                                                  and_(House.min_days <= differ_days, House.max_days == 0)))
        else:
            # 用户没有输入结束时间则显示所有信息
            houses_first = House.query.filter()
        if area_id:
            # 如果用户选择了区域信息
            houses_second = houses_first.filter(House.area_id == int(area_id))
        else:
            # 没有选择
            houses_second = houses_first
        # 过滤订单中的房源：待支付和已支付状态
        orders_filter = Order.query.filter(Order.status.in_(["WAIT_PAYMENT", "PAID", "WAIT_ACCEPT"])).all()
        # 去重房源id，因为过滤条件为待支付和已置夫，但还有完成后的订单记录，所以需要去重
        orders_filter_ids = set([order_filter.house_id for order_filter in orders_filter])
        houses_third = houses_second.filter(~House.id.in_(orders_filter_ids))
        # 排序
        # 新房源
        if sk == 'new':
            houses_final = houses_third.order_by(desc('update_time'))
        # 入住最多
        elif sk == 'booking':
            houses_final = houses_third.order_by(desc('order_count'))
        # 价格由高-低
        elif sk == 'price-inc':
            houses_final = houses_third.order_by('price')
        # 价格由低到高
        else:
            houses_final = houses_third.order_by(desc('price'))
        houses = houses_final.all()
        houses_info = [house.to_full_dict() for house in houses]
        return jsonify(houses_info)

ihome/templates/auth.html
{% extends 'base.html' %}

{% block title %}
    爱家-实名认证
{% endblock %}


{% block css %}
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/profile.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">实名认证</h3>
                <a class="nav-btn fl" href="{{ url_for('user.my') }}"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
        </div>
        <div class="menus-con">
            <ul class="menus-list">
                <li>
                    <div class="menu-title">
                        <h3>认证信息</h3>
                    </div>
                    <div class="menu-content">
                        <form id="form-auth" method="post">
                            <div class="form-group">
                                <label for="real-name">真实姓名</label>
                                <input type="text" class="form-control" name="real_name" id="real-name" >
                            </div>
                            <div class="form-group">
                                <label for="id-card">身份证号码</label>
                                <input type="text" class="form-control" name="id_card" id="id-card">
                            </div>
                            <div class="error-msg"><i class="fa fa-exclamation-circle"></i>信息填写不完整，请补全信息</div>
                            <input type="submit" class="btn btn-success" value="保存">
                        </form>
                    </div>
                </li>
            </ul>
        </div>
        <div class="popup_con">
            <div class="popup">
                <p>保存成功！</p>
            </div>

            <div class="mask"></div>
        </div>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/jquery.form.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/ihome/auth.js"></script>
{% endblock %}
    

ihome/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="icon" href="/static/favicon.ico" type="image/x-icon" />
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}
{% block js %}
<script src="/static/js/jquery.min.js"></script>
<script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
<script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
{% endblock %}
</body>
</html>

ihome/templates/booking.html
{% extends 'base.html'%}

{% block title %}
   爱家-预订
{% endblock %}

{% block css %}
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/booking.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">预 订</h3>
                <a class="nav-btn fl" href="#" onclick="hrefBack();"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
        </div>
        <div class="house-info">
            <img src="">
            <div class="house-text">
                <h3>房屋标题</h3>
                <p>￥<span>300</span>/晚</p>
            </div>
        </div>
        <div class="select-date">
            <div class="select-date-header">入住时间</div>
            <div class="input-daterange input-group">
                <input type="text" class="input-sm form-control" id="start-date" />
                <span class="input-group-addon">至</span>
                <input type="text" class="input-sm form-control" id="end-date" />
            </div>
        </div>
        <div class="submit-order">
            <span class="order-amount">订单总额：￥<span></span></span>
            <span class="submit-btn">提交订单</span>
        </div>
    </div>
    <div class="popup_con">
        <div class="popup">
            <p>日期有误，请重新选择！</p>
        </div>
        <div class="mask"></div>
    </div>
{% endblock %}

{% block js %}
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/ihome/booking.js"></script>
{% endblock %}
    

ihome/templates/detail.html
{% extends 'base.html' %}

{% block title %}
    爱家-房间信息
{% endblock %}

{% block css %}
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/swiper/css/swiper.min.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/detail.css" rel="stylesheet">
{% endblock %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title></title>

{% block content %}
    <div class="container">
        <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">房间信息</h3>
                <a class="nav-btn fl" href="#" onclick="hrefBack();"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
        </div>
        <div class="swiper-container">
            <ul class="swiper-wrapper">

            </ul>
            <div class="swiper-pagination"></div>
            <div class="house-price">￥<span>300</span>/晚</div>
        </div>
        <div class="detail-con">
            <div class="detail-header layout-style">
                <h2 class="house-title">房屋标题</h2>
                <div class="landlord-pic"><img src="/static/images/landlord01.jpg"></div>
                <h2 class="landlord-name">房东： <span>房东姓名</span></h2>
            </div>
            <div class="house-info layout-style">
               <h3>房屋地址</h3>
               <ul class="house-info-list text-center">
                    <li>地址内容中关村</li>
               </ul>
            </div>
            <ul class="house-type layout-style">
                <li>
                    <span class="icon-house"></span>
                    <div class="icon-text">
                        <h3>出租6间</h3>
                        <p>房屋面积:200平米</p>
                        <p>房屋户型:三室两厅两卫</p>
                    </div>
                </li>
                <li>
                    <span class="icon-user"></span>
                    <div class="icon-text">
                        <h3>宜住10人</h3>
                    </div>
                </li>
                <li>
                    <span class="icon-bed"></span>
                    <div class="icon-text">
                        <h3>卧床配置</h3>
                        <p>双人床两张</p>
                    </div>
                </li>
            </ul>
            <div class="house-info layout-style">
                <h3>房间详情</h3>
                <ul class="house-info-list">
                    <li>收取押金<span>2000</span></li>
                    <li>最少入住天数<span>1</span></li>
                    <li>最多入住天数<span>无限制</span></li>
                </ul>
            </div>
            <div class="house-facility layout-style">
                <h3>配套设施</h3>
                <ul class="house-facility-list clearfix">

                </ul>
            </div>
            <div class="house-info layout-style">
                <h3>评价信息</h3>
                <ul class="house-comment-list">
                    <li>
                        <p>用户名<span class="fr">2016-11-11 20:00:00</span></p>
                        <p>感觉不错</p>
                    </li>
                </ul>
            </div>
        </div>
        <a class="book-house" href="#">即刻预定</a>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/swiper/js/swiper.jquery.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/template.js"></script>
    <script src="/static/js/ihome/detail.js"></script>
{% endblock %}

ihome/templates/index.html
{% extends 'base.html'%}

{% block title %}
    家
{% endblock %}

{% block css %}
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/swiper/css/swiper.min.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/index.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="top-bar">
            <img class="logo fl" src="/static/images/logo@128x59.png">
            <div class="register-login fr">
                <a class="btn top-btn btn-theme" href="{{ url_for('user.register')}}">注册</a>
                <a class="btn top-btn btn-theme" href="{{ url_for('user.login') }}">登录</a>
            </div>
            <div class="user-info fr"><span><i class="fa fa-user fa-lg"></i></span> <a class="user-name" href="{{ url_for('user.my')}}"></a></div>
        </div>
        <div class="swiper-container">
            <div class="swiper-wrapper">

            </div>
            <div class="swiper-pagination"></div>
        </div>
        <div class="search-bar">
            <button class="filter-btn" type="button" data-toggle="modal" data-target="#area-modal"><span class="fl" id="area-btn">选择城区</span><span class="fr"><i class="fa fa-map-marker fa-lg fa-fw"></i></span></button>
            <button class="filter-btn" type="button" data-toggle="modal" data-target="#start-date-modal"><span class="fl" id="start-date-btn">入住日期</span><span class="fr"><i class="fa fa-calendar fa-lg fa-fw"></i></span></button>
            <button class="filter-btn end-date" type="button" data-toggle="modal" data-target="#end-date-modal"><span class="fl" id="end-date-btn">离开日期</span><span class="fr"><i class="fa fa-calendar fa-lg fa-fw"></i></span></button>
            <a class="btn search-btn btn-theme" href="#" onclick="goToSearchPage(this);" area-id="" start-date="" end-date="">搜索</a>
            <div class="modal fade" id="area-modal" tabindex="-1" role="dialog" aria-labelledby="area-label">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="area-label">选择城区</h4>
                        </div>
                        <div class="modal-body">
                            <div class="area-list">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="start-date-modal" tabindex="-1" role="dialog" aria-labelledby="start-date-label">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="start-date-label">入住日期</h4>
                        </div>
                        <div class="modal-body">
                            <div class="date-select" id="start-date"></div>
                            <input type="hidden" id="start-date-input">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-theme" onclick="setStartDate();">确定</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal fade" id="end-date-modal" tabindex="-1" role="dialog" aria-labelledby="end-date-label">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="end-date-label">离开日期</h4>
                        </div>
                        <div class="modal-body">
                            <div class="date-select" id="end-date"></div>
                            <input type="hidden" id="end-date-input">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-theme" onclick="setEndDate();">确定</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/swiper/js/swiper.jquery.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/template.js"></script>
    <script src="/static/js/ihome/index.js"></script>
{% endblock %}
    

ihome/templates/my.html
{% extends 'base.html' %}

{% block title %}
爱家-我的爱家
{% endblock %}

{% block css %}
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/my.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">我的爱家</h3>
                <a class="nav-btn fl" href="{{ url_for('order.index') }}"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
        </div>
        <div class="menus-con">
            <ul class="menus-list">
                <li>
                    <div class="menu-title">
                        <h3>个人信息</h3>
                        <a class="fr" href="{{ url_for('user.profile') }}">修改</a>
                    </div>
                    <div class="menu-content">
                        <img id="user-avatar" src="">
                        <div class="menu-text">
                            <h3>用户名：<span id="user-name"></span></h3>
                            <h5>手机号：<span id="user-mobile"></span></h5>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="{{ url_for('order.my_order') }}"><h3>我的订单</h3></a>
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="{{ url_for('user.auth') }}"><h3>实名认证</h3></a>
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="{{ url_for('house.my_house') }}"><h3>我的房源</h3></a>
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="{{ url_for('order.cu_order') }}"><h3>客户订单</h3></a>
                    </div>
                </li>
                <li>
                    <div class="menu-title menu-radius">
                        <a href="#" onclick="logout();" >退出</a>
                    </div>
                </li>
            </ul>
        </div>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/ihome/my.js"></script>
{% endblock %}

ihome/templates/search.html
{% extends 'base.html' %}

{% block title %}
爱家-房源
{% endblock %}

{% block css %}
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
    <link href="/static/css/ihome/search.css" rel="stylesheet">
{% endblock %}

{% block content %}
 <div class="container">
        <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">房 源</h3>
                <a class="nav-btn fl" href="{{ url_for('order.index')}}"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
            <ul class="filter-title-bar">
                <li class="filter-title">
                    <span>入住日期</span>
                    <span><i class="fa fa-angle-down"></i></span>
                    <span class="split-line fr">|</span>
                </li>
                <li class="filter-title">
                    <span>位置区域</span>
                    <span><i class="fa fa-angle-down"></i></span>
                    <span class="split-line fr">|</span>
                </li>
                <li class="filter-title">
                    <span>最新上线</span>
                    <span><i class="fa fa-angle-down"></i></span>
                </li>
            </ul>
            <div class="filter-item-bar">
                <div class="filter-item filter-date">
                    <div class="input-daterange input-group">
                        <input type="text" class="input-sm form-control" id="start-date" />
                        <span class="input-group-addon">至</span>
                        <input type="text" class="input-sm form-control" id="end-date" />
                    </div>
                </div>
                <ul class="filter-item filter-area">

                </ul>
                <ul class="filter-item filter-sort">
                    <li class="active" sort-key="new">最新上线</li>
                    <li sort-key="booking">入住最多</li>
                    <li sort-key="price-inc">价格 低-高</li>
                    <li sort-key="price-des">价格 高-低</li>
                </ul>
            </div>
        </div>
        <div class="display-mask"></div>
        <ul class="house-list">
           {% raw %}
            <script id="house_item_list" type="text/html">
                {{if houses.length}}
                {{each houses as house}}
                <li class="house-item">
                    <a href="/house/house_detail/{{house.id}}/"><img src="/static/media/{{house['images'][0]}}"></a>
                    <div class="house-desc">
                        <div class="landlord-pic"><img src="/static/media/{{house.user_avatar}}"></div>
                        <div class="house-price">￥<span>{{house.price}}</span>/晚</div>
                        <div class="house-intro">
                            <span class="house-title">{{house.title}}</span>
                            <em>出租{{house.room_count}}间 - {{house.order_count}}次入住 - {{house.address}}</em>
                        </div>
                    </div>
                </li>
                {{/each}}
                {{else}}
                暂无搜索结果
                {{/if}}
            </script>
            {% endraw %}
        </ul>
        <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/template.js"></script>
    <script src="/static/js/ihome/search.js"></script>
{% endblock %}